language: node_js
node_js:
  - "6"

script:
  - npm run build   # Will also perform the tests

notifications:
  email: false

deploy:
  provider: surge
  project: ./build/
  domain: secret-santa.surge.sh
